# Generated by Django 4.2.4 on 2023-08-25 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elon.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_childcategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Elonning nomi')),
                ('body', models.TextField(verbose_name='Elonning contente')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Narxi')),
                ('country_code', models.CharField(choices=[('+1', 'USA'), ('+44', 'UK'), ('+33', 'France'), ('+99', 'UZ'), ('+7', 'RU'), ('+7', 'QZ')], max_length=5)),
                ('image', models.ImageField(blank=True, upload_to=elon.utilities.get_timed_path, verbose_name='rasm')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aftor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.childcategory', verbose_name='Elon category')),
            ],
            options={
                'verbose_name': 'E`lon',
                'verbose_name_plural': 'E`lonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=elon.utilities.get_timed_path, verbose_name='qo`shimcha rasm')),
                ('elon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elon.elon', verbose_name='elon')),
            ],
            options={
                'verbose_name': 'Qo`shimcha rasm',
                'verbose_name_plural': 'Qo`shimcha rasmlar',
            },
        ),
    ]
