# Generated by Django 4.2.4 on 2023-09-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon',
            name='body',
            field=models.TextField(verbose_name='Elonning contenti'),
        ),
    ]
