# Generated by Django 4.2.4 on 2023-08-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category nomi')),
                ('order', models.SmallIntegerField(default=0, verbose_name='navbati')),
            ],
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Bola Category',
                'verbose_name_plural': 'Bola Categoriyalar',
                'ordering': ['order', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('category.category',),
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Super Category',
                'verbose_name_plural': 'Super Categoriyalar',
                'ordering': ['order', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('category.category',),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category.supercategory', verbose_name='Super category'),
        ),
    ]
