# Generated by Django 4.2.4 on 2023-08-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childcategory',
            options={'ordering': ['parent_category__order', 'order', 'name'], 'verbose_name': 'Bola Category', 'verbose_name_plural': 'Bola Categoriyalar'},
        ),
    ]
