# Generated by Django 4.2.4 on 2023-09-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elon', '0002_alter_elon_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='author')),
                ('body', models.TextField(verbose_name='Comment body')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ekranga chiqsinmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yozilgan sana')),
                ('elon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elon.elon', verbose_name='E`lon')),
            ],
            options={
                'verbose_name': 'Kommentariya',
                'verbose_name_plural': 'Kommentariyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
